world_frame: map
use_tf_transforms: true
use_freespace_pointcloud: true
tsdf_voxels_per_side: 16
tsdf_voxel_size: 0.15
max_ray_length_m: 30.0
min_ray_length_m: 0.20
truncation_distance: 0.45
voxel_carving_enabled: true
use_sparsity_compensation_factor: true
sparsity_compensation_factor: 20.0
color_mode: colors
verbose: false
update_mesh_every_n_sec: 0.0
mesh_min_weight: 0.0001
slice_level: 0.15
method: fast
integration_order_mode: sorted
max_consecutive_ray_collisions: 0
publish_slices: false
publish_pointclouds: true
allow_clear: true
pointcloud_queue_size: 20
min_time_between_msgs_sec: 0.05
publish_tsdf_info: false
publish_traversable: true
traversability_radius: 0.20
enable_icp: false
timestamp_tolerance_sec: 0.05
publish_tsdf_map: false
publish_esdf_map: false
esdf_max_distance_m: 2.0
clear_sphere_for_planning: false
max_weight: 100
clearing_ray_weight_factor: 0.05
weight_ray_by_range: false
occupancy_min_distance_voxel_size_factor: 1.0
